post_install() {
	local HOMEDIR=/var/lib/octoprint
	getent group octoprint > /dev/null || groupadd octoprint
	getent passwd octoprint > /dev/null || useradd -d $HOMEDIR -g octoprint -s /usr/bin/nologin octoprint
	usermod -a -G octoprint,network,uucp,tty octoprint
	mkdir -p $HOMEDIR
	chmod 700 $HOMEDIR
	chown -R octoprint:octoprint $HOMEDIR
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo "You may want to remove octoprint user and group"
}
